
import type { Event, Venue, Thread } from '@/lib/types';

const now = new Date();
const getFutureDate = (days: number, hours: number = 0) => {
    const date = new Date();
    date.setDate(now.getDate() + days);
    date.setHours(hours, 0, 0, 0);
    return date.toISOString();
}

export const placeholderVenues: (Omit<Venue, 'id' | 'createdAt' | 'updatedAt' > & { id: string })[] = [
  {
    id: 'the-fillmore',
    name: 'The Fillmore',
    type: 'venue',
    description: 'A legendary music venue in San Francisco, known for its historic past and intimate concert experiences.',
    address: '1805 Geary Blvd, San Francisco, CA 94115',
    neighborhood: 'Fillmore District',
    location: { latitude: 37.7842, longitude: -122.4331 },
    openingHours: 'Varies by show',
    priceLevel: 3,
    tags: ['music', 'concert', 'historic'],
    coverImageUrl: 'https://images.unsplash.com/photo-1559819234-8be7cac3aich?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    createdBy: 'system',
    verified: true,
    isFeaturedOnLanding: true,
  },
  {
    id: 'zeitgeist',
    name: 'Zeitgeist',
    type: 'bar',
    description: 'A classic SF beer garden with a huge selection of craft beers, a punk rock vibe, and a spacious outdoor patio.',
    address: '199 Valencia St, San Francisco, CA 94103',
    neighborhood: 'Mission District',
    location: { latitude: 37.7699, longitude: -122.4221 },
    openingHours: '11:30 AM - 2:00 AM',
    priceLevel: 2,
    tags: ['beer garden', 'patio', 'craft beer', 'dive bar'],
    coverImageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    createdBy: 'system',
    verified: true,
    isFeaturedOnLanding: true,
  },
  {
    id: 'four-barrel-coffee',
    name: 'Four Barrel Coffee',
    type: 'cafe',
    description: 'A bustling, hip coffee shop in the Mission that roasts its own beans and serves artisanal espresso drinks.',
    address: '375 Valencia St, San Francisco, CA 94103',
    neighborhood: 'Mission District',
    location: { latitude: 37.7676, longitude: -122.4221 },
    openingHours: '7:00 AM - 6:00 PM',
    priceLevel: 2,
    tags: ['coffee', 'artisanal', 'roastery'],
    coverImageUrl: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    createdBy: 'system',
    verified: true,
    isFeaturedOnLanding: true,
  },
  {
    id: 'de-young-museum',
    name: 'de Young Museum',
    type: 'gallery',
    description: 'Fine arts museum located in Golden Gate Park, showcasing American art from the 17th through the 21st centuries, international contemporary art, textiles, and costumes.',
    address: '50 Hagiwara Tea Garden Dr, San Francisco, CA 94118',
    neighborhood: 'Golden Gate Park',
    location: { latitude: 37.7715, longitude: -122.4687 },
    openingHours: '9:30 AM - 5:15 PM (Tue-Sun)',
    priceLevel: 3,
    tags: ['art', 'museum', 'culture', 'park'],
    coverImageUrl: 'https://images.unsplash.com/photo-1588697137992-0f9c6c72d5e3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    createdBy: 'system',
    verified: true,
    isFeaturedOnLanding: false,
  },
];

export const placeholderEvents: (Omit<Event, 'id' | 'createdAt' | 'updatedAt' | 'startTime' | 'endTime'> & { id: string, startTime: string, endTime?: string })[] = [
  {
    id: 'indie-fest-2024',
    title: 'IndieFest 2024 at The Fillmore',
    description: 'An evening celebrating the best up-and-coming indie rock bands from the Bay Area and beyond. Full lineup to be announced.',
    category: 'Music',
    tags: ['indie', 'live music', 'rock'],
    startTime: getFutureDate(10, 20), // 10 days from now at 8 PM
    endTime: getFutureDate(10, 23),
    timezone: 'PST',
    venueId: 'the-fillmore',
    hostId: 'system-user',
    coverImageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    priceType: 'paid',
    priceMin: 45,
    status: 'published',
    visibility: 'public',
    approvalStatus: 'approved',
    createdBy: 'system',
    isFeaturedOnLanding: true,
    priorityScore: 100,
    neighborhood: 'Fillmore District',
    venueName: 'The Fillmore',
    hostName: 'SF Music Scene',
    stats: { interestedCount: 102, goingCount: 65, savedCount: 88 },
  },
  {
    id: 'sf-tech-mixer-ai',
    title: 'SF Tech Mixer: The Future of AI',
    description: 'Join industry leaders, developers, and investors for a night of networking and discussion on the latest trends in Artificial Intelligence.',
    category: 'Networking',
    tags: ['tech', 'ai', 'networking', 'startups'],
    startTime: getFutureDate(5, 18), // 5 days from now at 6 PM
    endTime: getFutureDate(5, 21),
    timezone: 'PST',
    venueId: 'zeitgeist', // Using Zeitgeist as a placeholder venue
    hostId: 'system-user',
    coverImageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=2232&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    priceType: 'free',
    status: 'published',
    visibility: 'public',
    approvalStatus: 'approved',
    createdBy: 'system',
    isFeaturedOnLanding: true,
    priorityScore: 90,
    neighborhood: 'Mission District',
    venueName: 'Zeitgeist',
    hostName: 'Bay Area Techies',
    stats: { interestedCount: 250, goingCount: 120, savedCount: 150 },
  },
  {
    id: 'weekend-art-show',
    title: 'Weekend Art Showcase: Local Artists',
    description: 'Discover the vibrant local art scene. Paintings, sculptures, and mixed media from talented San Francisco artists will be on display and for sale.',
    category: 'Arts',
    tags: ['art', 'gallery', 'local artists', 'culture'],
    startTime: getFutureDate(3, 11), // This coming Saturday at 11 AM
    endTime: getFutureDate(3, 17),
    timezone: 'PST',
    venueId: 'de-young-museum',
    hostId: 'system-user',
    coverImageUrl: 'https://images.unsplash.com/photo-1531981284873-ce55ca41a3a1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    priceType: 'donation',
    status: 'published',
    visibility: 'public',
    approvalStatus: 'approved',
    createdBy: 'system',
    isFeaturedOnLanding: true,
    priorityScore: 80,
    neighborhood: 'Golden Gate Park',
    venueName: 'de Young Museum',
    hostName: 'SF Art Collective',
    stats: { interestedCount: 88, goingCount: 42, savedCount: 71 },
  },
  {
    id: 'farmers-market-ferry',
    title: 'Ferry Plaza Farmers Market',
    description: 'A vibrant farmers market with fresh produce, artisan foods, and beautiful views of the bay. A true taste of Northern California.',
    category: 'Food & Drink',
    tags: ['farmers market', 'local food', 'outdoors'],
    startTime: getFutureDate(3, 9), // This coming Saturday at 9 AM
    endTime: getFutureDate(3, 14),
    timezone: 'PST',
    hostId: 'system-user',
    coverImageUrl: 'https://images.unsplash.com/photo-1587624564943-5f1428615455?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    priceType: 'free',
    status: 'published',
    visibility: 'public',
    approvalStatus: 'approved',
    createdBy: 'system',
    isFeaturedOnLanding: false,
    priorityScore: 70,
    neighborhood: 'Embarcadero',
    hostName: 'CUESA',
    stats: { interestedCount: 300, goingCount: 150, savedCount: 200 },
  },
];


export const placeholderThreads: (Omit<Thread, 'id' | 'createdAt' | 'updatedAt' | 'lastActivityAt'> & { id: string })[] = [
    {
        id: 'best-burrito-in-mission',
        title: 'Settle the debate: What is the BEST burrito in the Mission?',
        body: "I'm on a quest to find the ultimate burrito in the Mission and I need your help. I've tried La Taqueria (no rice, controversial!), El Farolito (the long lines!), and Pancho Villa. They're all amazing, but which one is truly the king? Cast your vote and defend your choice!",
        topic: 'neighborhoods',
        tags: ['food', 'mission', 'burrito', 'debate'],
        createdBy: 'system-user-1',
        authorInfo: {
            displayName: 'BurritoMaster',
            photoURL: 'https://i.pravatar.cc/150?u=burrito',
        },
        replyCount: 28,
        likeCount: 42,
    },
    {
        id: 'sutro-baths-hike',
        title: 'Hidden photo spots at Sutro Baths?',
        body: "Planning a sunset hike at Sutro Baths this weekend. I've been a few times but feel like I'm missing some of the more hidden, dramatic photo opportunities. Any photographers out there have tips on where to go beyond the main ruins?",
        topic: 'general',
        tags: ['hiking', 'photography', 'outdoors', 'sunset'],
        relatedVenueId: 'de-young-museum', // close enough for a placeholder
        createdBy: 'system-user-2',
        authorInfo: {
            displayName: 'Shutterbug',
            photoURL: 'https://i.pravatar.cc/150?u=shutterbug',
        },
        replyCount: 12,
        likeCount: 31,
    },
    {
        id: 'looking-for-dnd-group',
        title: 'D&D Group Looking for 1-2 More Players (Noe Valley)',
        body: "Our regular Dungeons & Dragons group is looking for one or two new players to join a new campaign. We play every other Tuesday evening in Noe Valley. We're a friendly, inclusive group, new players welcome! We focus more on roleplaying than rules-lawyering. Send me a message if you're interested!",
        topic: 'clubs',
        tags: ['dnd', 'gaming', 'tabletop', 'rpg'],
        createdBy: 'system-user-3',
        authorInfo: {
            displayName: 'DungeonMaster',
            photoURL: 'https://i.pravatar.cc/150?u=dnd',
        },
        replyCount: 5,
        likeCount: 15,
    }
];
